### ISSUE TITLE
Inlog scherm wordt groter wanneer er input is (niet heel urgent)

### ISSUE THREAD

**Issue by Jurian-24** [JoeriDekker/Project-D#17]
Wanneer je in het begin scherm typt wordt de input container groter. Zie voor en na fotos

<img width="350" alt="Screenshot 2024-05-21 at 19 41 52" src="https://github.com/JoeriDekker/Project-D/assets/14735632/a0446dbc-47cd-4864-8c5d-72460855e3a8">

<img width="350" alt="Screenshot 2024-05-21 at 19 42 08" src="https://github.com/JoeriDekker/Project-D/assets/14735632/f9301b87-b068-49e7-9c56-50f9d94be9f6">

**Comment by Failfan13** [comment]
geen bug maar een feature : )

**Comment by nietrenswens** [comment]
@Failfan13 Heeft dit opgepakt en opgelost in de bijhorende branch, is sluit deze issue.
