### ISSUE TITLE
Foutmelding terwijl peil goed is

### ISSUE THREAD

**Issue by nietrenswens** [JoeriDekker/Project-D#36]
Op de huidige versie van het prototype (live website) krijg ik een foutmelding als ik inlog over het grondwaterpeil. Maar volgens de gegevens is het grondwaterpeil goed?

**Comment by Jurian-24** [comment]
Ik fix hem vanmiddag

**Comment by Jurian-24** [comment]
Kan je miss een foto posten van de melding of de stappen uitleggen hoe je bij de bug bent gekomen dan kan ik het sneller fixen😎

**Comment by nietrenswens** [comment]
1. Navigeer naar de website (je weet welke)
2. Log in met de standaard gegevens.
3. Aanschouw de error
![afbeelding](https://github.com/JoeriDekker/Project-D/assets/6216905/c6c9d361-55c1-4a23-8b13-fc5c1476440b)
![afbeelding](https://github.com/JoeriDekker/Project-D/assets/6216905/00e6032a-0dbf-4250-8d67-9762efce3f45)

**Comment by nietrenswens** [comment]
Het is te tijdrovend om dit op het moment nog te fixen
